# Generated by Django 3.2.5 on 2021-07-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teacher_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../static/images/avatar.png', upload_to=None, verbose_name='Profile Picture'),
        ),
    ]
