# Generated by Django 3.2.5 on 2021-07-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_teacher_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject_1',
            field=models.TextField(max_length=100, verbose_name='Subject_1'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject_2',
            field=models.TextField(max_length=100, verbose_name='Subject_2'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject_3',
            field=models.TextField(max_length=100, verbose_name='Subject_3'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject_4',
            field=models.TextField(max_length=100, verbose_name='Subject_4'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject_5',
            field=models.TextField(max_length=100, verbose_name='Subject_5'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, default='./static/images/avatar.png', upload_to=None, verbose_name='Profile Picture'),
        ),
    ]
