# Generated by Django 3.2.5 on 2021-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210727_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
