# Generated by Django 3.2.5 on 2021-07-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_csv_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Subject_1',
            field=models.TextField(blank=True, max_length=100, verbose_name='Subject_1'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject_2',
            field=models.TextField(blank=True, max_length=100, verbose_name='Subject_2'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject_3',
            field=models.TextField(blank=True, max_length=100, verbose_name='Subject_3'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject_4',
            field=models.TextField(blank=True, max_length=100, verbose_name='Subject_4'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject_5',
            field=models.TextField(blank=True, max_length=100, verbose_name='Subject_5'),
        ),
    ]
